# Generated by Django 3.2.25 on 2025-02-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_blood_groups', to='accounts.bloodgroup')),
                ('donated_organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_organs', to='accounts.organ')),
                ('donor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_record', to='accounts.userdetails')),
            ],
        ),
    ]
