# Generated by Django 3.2.25 on 2025-02-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('place', models.CharField(default=1, max_length=50)),
                ('district', models.CharField(default=1, max_length=50)),
                ('state', models.CharField(default=1, max_length=50)),
                ('pin', models.CharField(default=1, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bloodgroup')),
                ('organ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organ')),
            ],
        ),
    ]
