# Generated by Django 3.2.25 on 2025-02-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organ')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.bloodgroup')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organ')),
            ],
        ),
    ]
