# Generated by Django 3.2.25 on 2025-02-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor_Donor',
            new_name='DoctorDonor',
        ),
    ]
